export const VoiceChangerType = {
  TEXT: 0,
  UPLOAD: 1,
  RECORD: 2
}

export const Language = {
  AUTO: 0,
  ENGLISH: 1,
  HINDI: 2,
  PORTUGUESE: 3,
  CHINESE: 4,
  SPANISH: 5,
  FRENCH: 6,
  GERMAN: 7,
  JAPANESE: 8,
  ARABIC: 9,
  RUSSIAN: 10,
  KOREAN: 11,
  INDONESIAN: 12,
  ITALIAN: 13,
  DUTCH: 14,
  TURKISH: 15,
  POLISH: 16,
  SWEDISH: 17,
  FILIPINO: 18,
  MALAY: 19,
  ROMANIAN: 20,
  UKRAINIAN: 21,
  GREEK: 22,
  CZECH: 23,
  DANISH: 24,
  FINNISH: 25,
  BULGARIAN: 26,
  CROATIAN: 27,
  SLOVAK: 28,
  TAMIL: 29
}

export const UPLOADTYPE = {
  DIRECT: 0,
  MUTI_PART: 1
}

export const VoiceTranslatorType = {
  VIDEO: 0,
  URL: 1
}

export const AudioContentFrom = {
  TEXT: 'text',
  AUDIO: 'audio'
}


// 任务状态
export const TaskStatus= {
  CREATING : 0,
  FAILED: 1,
  SUCCEED: 2
}

// 上传限制
export const UPLOAD = {
  MAX_IMAGE_WIDTH: 1280, //为了满足ios最大canvas像素限制
  MAX_IMAGE_HEIGHT: 1280,
  MAX_IMAGE_WIDTH_PC: 2048,
  MAX_IMAGE_HEIGHT_PC: 2048,
  MAX_VIDEO_WIDTH: 1920,
  MAX_VIDEO_HEIGHT: 1920,
  MIN_VIDEO_WIDTH: 160,
  MIN_VIDEO_HEIGHT: 160,
  MAX_DURATION_BETA: 10,
  MAX_IMAGE_SIZE: 10 * 1024 * 1024,
  BACK_MAX_SIZE: 4 * 1024 * 1024,
  MAX_GIF_SIZE: 15 * 1024 * 1024,
  MAX_VIDEO_SIZE_BETA: 500,
  ALLOWED_EXTS: ['avi', 'mov', 'mp4', 'jpg', 'jpeg', 'png', 'gif'],
  ALLOWED_VIDEO_TYPES: ['x-msvideo', 'quicktime', 'mp4', 'mov']
}

export const CDN_HOST = 'https://files.img-tools.app'

// 文件类型
export const FILE_TYPE = {
  MATERIAL: 'MATERIAL',
  FACE: 1,
  RESOURCE_COMPLAINT_PROOF: 'RESOURCE_COMPLAINT_PROOF',
  BANNER_COVER: 'BANNER_COVER', 
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  APP_VERSION: 'APP_VERSION',
  AVATAR: 'AVATAR',
  PRE_FACE_SHIFT: 'PRE_FACE_SHIFT',
  PUBLIC_MATERIAL: 'PUBLIC_MATERIAL',
  PUBLIC_MATERIAL_COVER: 'PUBLIC_MATERIAL_COVER',
  DEMO: 'DEMO',
  FEATURE_ITEM_COVER: 'FEATURE_ITEM_COVER',
  TEMPORARY_FACE: 'TEMPORARY_FACE',
  TEMPORARY_MATERIAL: 'TEMPORARY_MATERIAL', 
  PARSE_FACE: 'PARSE_FACE',
  INPAINTING_IMAGE: 'INPAINTING_IMAGE',
  INPAINTING_IMAGE_MASK: 'INPAINTING_IMAGE_MASK',
  EXTEND_IMAGE_COMBINED_IMAGE_MASK: 'EXTEND_IMAGE_COMBINED_IMAGE_MASK',
  EXTEND_IMAGE_ORIGIN_IMAGE: 'EXTEND_IMAGE_ORIGIN_IMAGE',
  EXTEND_IMAGE_COMBINED_IMAGE: 'EXTEND_IMAGE_COMBINED_IMAGE',
  REMOVE_BACKGROUND_ORIGIN_IMAGE: 'REMOVE_BACKGROUND_ORIGIN_IMAGE',
  SUPER_RESOLUTION_ORIGIN_IMAGE: 'SUPER_RESOLUTION_ORIGIN_IMAGE',
  ANIME_STYLIZE_PHOTO: 'ANIME_STYLIZE_PHOTO',
  TALKING_PHOTO_AUDIO: 'TALKING_PHOTO_AUDIO',
  TALKING_PHOTO: 'TALKING_PHOTO',
  VOICE_TRANSLATE_SOURCE: 'VOICE_TRANSLATE_SOURCE'
}
